### ISSUE TITLE
SetupWizard Bugs & Follow-up tasks

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#10126]
## Overview

This is going to maintain a task list, notes, and discussion around several bugs. I am putting a lot of this in the same place as the solutions to many of the reported bugs during our last bug bash will likely be fixed together and are likely related to the same root issues.

```[tasklist]
### Tasks
- [x] Handle `apiError` such that it provides a "Start Over" button which will delete the `savedState` value where the interpreted machine is serialized between transitions (there is a path in the state machine -- send it the `START_OVER` event)
[Notion Report: Getting stuck forever, no "start over"](https://www.notion.so/learningequality/Import-facility-flow-completely-fails-after-selection-of-device-to-import-from-if-the-selected-devic-248c03dce87b49c2b09fd2207ca25261?pvs=4) -
[Notion Report: Cannot go back from "Select Facility" page](https://www.notion.so/learningequality/Possible-to-get-into-a-state-in-the-import-facility-work-flow-where-you-cannot-go-back-5ee3bf6124ca4f2382bf55a5ccaf4803?pvs=4) -
- [x] Add a guard against transitioning beyond the credentials form -- likely this error is related to the already-entered username / password not being clear during navigation.
- [x] Import facility "Retry" button should provide better error handling, escape hatch to start over fresh.
- [x] In final steps of Facility Import -- be sure that the user selected at the end is set as the "Superuser" for the device
- [x] Update the SelectFacility page such that it automatically selects the first option and continues without loading the page at all if there is only one possible facility to choose from. Must ensure that "Go Back" then from the next page returns to the page *previous* to the  "Select Facility" page
- [x] The list of users on the Multiple Select is dim (as if disabled?) -- dig into the cause of this and make sure everything is legible and using proper contrasting colors per our design system
- [ x] Move the timeout in the polling function in `ImportIndividualUsers` so that it won't run until the previous poll call is resolved. Investigate that this is the case also in the `LoadingTaskPage`, `MultipleUsers`.
- [x] (tracked https://github.com/learningequality/kolibri/issues/10326)  **On my own:** The following reported by Peter: _"On my own - The full name field is supposed to accept up to 120 characters but entering more than 50 is causing an error"_ and I suspect it is likely going to be resolved somewhere in  `kolibri.core.device.serializers`. **Likely related** is that the full name field is not being saved to the user (see videos) [Video - Full name not being saved during provisioning](https://user-images.githubusercontent.com/79847249/222199710-85a35fbd-143d-4cd5-b3bf-9ae5c89ba5a5.mp4)  -_-_-_-  [Video - Failing on >50 characters](https://user-images.githubusercontent.com/79847249/222204048-a95d3be0-c156-4b9f-a36c-ffdc482316b9.mp4)  
- [x] Call the ZeroConf restart at the end of everything in SettingUpKolibri (fixed https://github.com/learningequality/kolibri/pull/10205)
- [x] Resolve this [comment re: params/facility_id stuff](https://github.com/learningequality/kolibri/pull/10139/files#r1125157030)
```

**Comment by radinamatic** [comment]
@nucleogenesis Please add the issue of the Device page missing (plugin not loaded?) after the facility import from another device. @pcenov mentioned it during his testing of the original PR, and I replicated yesterday during the bugbash.
