### ISSUE TITLE
Finalize file size work 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10158]
Complete remaining file size work after merging initial PR for string freeze purposes

```[tasklist]
### Tasks
- [x] Ensure lessons and quizzes have tests that ensure the response actually contains the correct file sizes ([PR comment](https://github.com/learningequality/kolibri/pull/10058#discussion_r1120876354))
- [x] Update endpoint to return either a detail endpoint that returns the map, or a list of `{"id": <id>, "file_size": <file_size>}` ([PR comment](https://github.com/learningequality/kolibri/pull/10058#discussion_r1120876775))
- [x] Fix incomplete quiz and lesson Vuex state [(PR comment)](https://github.com/learningequality/kolibri/pull/10058#discussion_r1120878580)
- [x] Add an empty `{}` as default state for reactivity ([PR comment](https://github.com/learningequality/kolibri/pull/10058#discussion_r1120879850))
```

Overall code review should also consider initial PR https://github.com/learningequality/kolibri/pull/10058

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/10452
