### ISSUE TITLE
Finalize sync schedule work

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10173]
This is a follow up issue to #9786 which has been slightly prematurely merged in order to get strings in before string freeze.

The following issues need to still be addressed:

```[tasklist]
### Tasks
- [x] Handle click events in the common status component by emitting an event that is handled in the parent component in order to avoid encoding facility specific navigation events in the core component (see https://github.com/learningequality/kolibri/pull/9786/files#r1122278683)
- [x] Reinstate disabling of register option: https://github.com/learningequality/kolibri/pull/9786/files#r1122279739
- [x] Add MANAGE_SYNC constant to `OPTIONS` so that it has a value rather than being `undefined`: https://github.com/learningequality/kolibri/pull/9786/files#r1122207691
- [x] Reinstate conditional display of the Register Menu option: https://github.com/learningequality/kolibri/pull/9786/files#r1122209233
- [x] Handle loading state for facility data: https://github.com/learningequality/kolibri/pull/9786/files#r1119538350
- [x] Handle unloaded network locations: https://github.com/learningequality/kolibri/pull/9786/files#r1122283756
- [x] Clean up validation warnings from KSelects: https://github.com/learningequality/kolibri/pull/9786/files#r1122285628
- [x] Check and resolve styling issues for KSelects: https://github.com/learningequality/kolibri/pull/9786#issuecomment-1438852763
- [x] Finalize editing/creation functionality to make sure fully functional
- [x] Add implementation and routing to device plugin as well as facility
```

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/10463
