### ISSUE TITLE
Finalize integration device connection testing

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10186]
As a followup to https://github.com/learningequality/kolibri/pull/10141 and https://github.com/learningequality/kolibri/pull/10155

```[tasklist]
### Tasks
- [x] Rebase https://github.com/learningequality/kolibri/pull/10133 and merge that PR
- [ ] https://github.com/learningequality/kolibri/issues/11018
- [ ] Add connection check when syncing to KDP or importing from Studio to verify internet connection and surface that feedback to the user
- [ ] Consolidate `useDevices` composables
```
