### ISSUE TITLE
Finalize learner storage notifications

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10184]
This is a followup to https://github.com/learningequality/kolibri/pull/10056 which was merged to get user strings merged before string freeze.

```[tasklist]
### Tasks
- [x] Make polling reactive to user logged in state, removing early return in poll function ([link](https://github.com/learningequality/kolibri/pull/10056/files#diff-f0d20dbe19423bd97d7aa86e34f39ba122e397094e9aabb714759e95ba124ad9R43))
- [x] ~Wire up `StorageNotification.vue` with appropriate data to show proper variations of notification message ([link](https://github.com/learningequality/kolibri/pull/10056/files#diff-155b7b2af6eb8f44179578e0b3670d02f3938df8170a9a2bcdaea7ff196dbcb7R70))~ **Replaced with** https://github.com/learningequality/kolibri/issues/10378
- [x] Properly handle cross-plugin routing ([link](https://github.com/learningequality/kolibri/pull/10056/files#r1094627926))
```

**Comment by vaibhav-1508** [comment]
Hey there! I would like to take up this issue, would you please assign me it to me?

**Comment by vaibhav-1508** [comment]
@bjester ?

**Comment by bjester** [comment]
Hi @vaibhav-1508, thanks for your interesting in contributing. Unfortunately, we don't yet have the data available that is needed to complete this issue. So it isn't quite ready to be completed.
