### ISSUE TITLE
Feature Request: Add --manifest-only option to exportcontent

### ISSUE THREAD

**Issue by tim-moody** [learningequality/kolibri#10384]
My understanding is that 0.16 will generate a channel manifest during 

`kolibri manage exportcontent`

My request is that you add an option that will not do the export of content but only generate the manifest. This manifest could then be used on another remote install to import from network the same set of content.

```[tasklist]
### Tasks
- [ ] Add --manifest-only command line option to the exportcontent management command
- [ ] If this option is selected, generate the manifest, but skip copying any files (channel database files, and content files)
- [ ] Write tests to confirm the --manifest-only behaviour
```

**Comment by rtibbles** [comment]
Thanks @tim-moody - I think this should be relatively feasible, the merging of the manifest files with sequential exports only happens within the manifest files themselves, and doesn't need access to the resources being on disk if I recall. I'll add this to our patch release milestone for 0.16.x.

**Comment by holta** [comment]
@rtibbles any idea if Kolibri 0.16 is expected in Q2 or Q3 or Q4?

If you happen to know anyway, _No Obligation!_

([Internet-in-a-Box](https://internet-in-a-box.org) is looking into stronger support for Kolibri, just a rough idea would be great if available!)

- PR iiab/iiab#3504

**Comment by rtibbles** [comment]
0.16 will be released in Q2. It is nearly feature complete, and we will start cutting betas rather than alphas in the very near future.

**Comment by holta** [comment]
> 0.16 will be released in Q2. It is nearly feature complete, and we will start cutting betas rather than alphas in the very near future.

@rtibbles any chance we ([Internet-in-a-Box](https://internet-in-a-box.org)) can help beta-test this channel manifest functionality in coming-weeks-or-so ?

If possible anyway, ideally !!

Thank you for considering 📚

**Comment by thesujai** [comment]
Looks interesting! I would love to implement this feature. Can you assign me this ticket? 
Just a little confused about exportcontent command that how is it working, I don't see it in the doc. Any relevant code for this?

**Comment by rtibbles** [comment]
It is a custom Django management command, implemented here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/management/commands/exportcontent.py

This would involve adding an option to the arg parser for the management command and then using that option to conditionalize the behaviour. It should default to `False` :)

As we've targeted this for the 2nd planned patch of the 0.16.x series, please branch from and target any work to the release-v0.16.x branch.

And thank you! I've assigned you!

**Comment by thesujai** [comment]
Alright, Thank you!

**Comment by rtibbles** [comment]
This has been fixed in #12059 - this will be released in the next patch release of 0.16 - 0.16.2. Which will be released on or before 2024-05-13.

**Comment by tim-moody** [comment]
Great. Thanks. I will use this to catalog channels installed for Internet in a Box installation presets.
