### ISSUE TITLE
Final Polish - Remote content browsing UI and ensuring full feature flow is to spec

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10448]
## Observed behavior
While the remote content browsing work is nearly finished, with most issues closed, there should be a "once over" and stitching together of the entire feature flow, and ensuring the front end is [to spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1904-19105&t=ywHecBxsNAJuJ3Ke-0), so we can ✅  this issue as complete.

```[tasklist]
### Tasks
- [x] Ensure that the Kolibri Library 'pin' is disabled and not clickable
- [x] Ensure that when there are no pinned devices, some unpinned devices are displayed rather than an empty section and a 'More' button
- [x] Ensure that when there are no pinned devices, we omit the 'More' header, which is superfluous.
- [ ] Ensure that guest users do not see "partial" information (i.e. headings that are empty or for page sections that they are not able to see; buttons associated with missing/irrelevant sections), etc.
```
