### ISSUE TITLE
Quizzes can display more attempts than questions

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10804]
Reported by S2S and in Flying Colors, there seem to be some cases where the number of responses in the coach quiz report is greater than the total number of questions, probably due to multiple attemptlogs per item being saved accidentally. 

The solution should attempt to fix historical data to consolidate the duplicate attempt logs via a data migration, rather than remediating the coach reports. It should also avoid reintroducing inefficient queries to uniquefy the attempts per item.
```[tasklist]
### Tasks
- [x] Improve debounce behaviour for log saving ensuring that the resolve/reject stack does not cross wires with subsequent invocations, see https://github.com/learningequality/studio/blob/unstable/contentcuration/contentcuration/frontend/shared/data/serverSync.js#L302 for example
- [x] Ensure that attempt log saves in the log API backend are unique for masterylog/item combination - this should prevent multiple attemptlogs being created
- [x] Add an upgrade task to consolidate attemptlogs for the same masterylog that have an identical item value
```
