### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11321]
## Summary

We extensively use `KResponsiveWindow` (provides reactive window's size information) as mixin in Kolibri. The latest version of [Kolibri Design System (KDS)](https://github.com/learningequality/kolibri-design-system) installed on the Kolibri's `develop` branch offers better alternative, `useKResponsiveWindow` composable. This issue encapsulates a group of issues whose common goal is to completely get rid of `KResponsiveWindow` mixin in favor of using `useKResponsiveWindow` composable in the whole Kolibri.

Note that the ways we import the mixin in our files are not always consistent, for example you may see:
- `import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';`
- `import KResponsiveWindowMixin from 'kolibri-design-system/lib/KResponsiveWindowMixin';`

You can use [Vue Devtools](https://devtools.vuejs.org/) and codebase search to find out pages that need to be previewed in the app based on the components/files you're modifying. Please test your changes before opening a pull request (see acceptance criteria).

## Acceptance criteria (for each one of the issues listed below)

- [ ] `useKResponsiveWindow` composable is used instead of `KResponsiveWindow` mixin in an area specified by a sub-issue
- [ ] All occurences of properties provided by `KResponsiveWindow` (`windowIsSmall`, `windowBreakpoint`, etc., see [the full list here]([url](https://develop--kolibri-design-system.netlify.app/kresponsivewindow/#overview))) are imported from `useKResponsiveWindow` composable in a file where `KResponsiveWindow` mixin is being removed
- [ ] Whatever logic was `KResponsiveWindow` mixin used for (for example, using different styling for mobile devices) is manually tested and still works as expected with `useKResponsiveWindow` composable
- [ ] There is a list of affected pages in a pull request description (e.g. their URLs)

## References
- [`KResponsiveWindow` documentation page](https://develop--kolibri-design-system.netlify.app/kresponsivewindow/#). Also see the "Usage" section to understand both approaches.
- Example of `KResponsiveWindow` mixin in Kolibri:
  - https://github.com/learningequality/kolibri/blob/b38ad516e99949b4d6826838dc16ef93f31c52dc/kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue#L197
  - https://github.com/learningequality/kolibri/blob/b38ad516e99949b4d6826838dc16ef93f31c52dc/kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue#L422
- Example of `useKResponsiveWindow` composable in Kolibri:
  - https://github.com/learningequality/kolibri/blob/b38ad516e99949b4d6826838dc16ef93f31c52dc/kolibri/core/assets/src/views/Navbar/NavbarLink.vue#L31
  - https://github.com/learningequality/kolibri/blob/b38ad516e99949b4d6826838dc16ef93f31c52dc/kolibri/core/assets/src/views/Navbar/NavbarLink.vue#L7
- [Vue's Composables Documentation](https://vuejs.org/guide/reusability/composables.html#composables)

## Sub-issues

```[tasklist]
### Sub-issues
- [ ] https://github.com/learningequality/kolibri/issues/11322
- [ ] https://github.com/learningequality/kolibri/issues/11323
- [ ] https://github.com/learningequality/kolibri/issues/11324
- [ ] https://github.com/learningequality/kolibri/issues/11325
- [ ] https://github.com/learningequality/kolibri/issues/11326
- [ ] https://github.com/learningequality/kolibri/issues/11327
- [ ] https://github.com/learningequality/kolibri/issues/11328
- [ ] https://github.com/learningequality/kolibri/issues/11329
- [ ] https://github.com/learningequality/kolibri/issues/11330
- [ ] https://github.com/learningequality/kolibri/issues/11331
- [ ] https://github.com/learningequality/kolibri/issues/11332
- [ ] https://github.com/learningequality/kolibri/issues/11333
- [ ] https://github.com/learningequality/kolibri/issues/11335
```

**Comment by MisRob** [comment]
Note that the current version of `useKResponsiveWindow` might be buggy on some occasions, e.g. https://github.com/learningequality/kolibri/issues/11212 is caused by it. This will be fixed soon https://github.com/learningequality/kolibri-design-system/pull/453

**Comment by MisRob** [comment]
If you'd like to contribute, please don't ask for an assignment of this issue, but rather in a sub-issue.

**Comment by thesujai** [comment]
Hey @MisRob, I was participating in [HactoberFest](https://hacktoberfest.com/).
Would it be possible for you to add a `hacktoberfest-accepted` label in my PRs for the sub-issues. I would be really thankful to you. As they asked we can ask the maintainers to add just the label in PR if they aren't participating in the fest.
Here is the link: https://hacktoberfest.com/participation/#maintainers
Its fine if for some reasons you aren't able to do so:)

**Comment by MisRob** [comment]
Hello @thesujai, I will reach out back in a few days in regards to Hactoberfest

**Comment by thesujai** [comment]
Okay @MisRob

**Comment by MisRob** [comment]
@thesujai Answered here https://github.com/learningequality/kolibri/discussions/11356#discussioncomment-7262009
