### ISSUE TITLE
Upgrade xstate to version 5.x

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#11614]
## Overview

The xstate library kolibri uses for some of the kolibri processes has released a new version v5.x that adds some features but introduces some breaking changes with version 4.x .

We should apply those changes to kolibri code before upgrading to v5. 
Also some of the new features (use of `can` in guards or the `fromPromise` helper can improve current machines code)

#### Description and outcomes
To be done in a future 0.16 patch release

#### Resources
- [Webinar](https://www.youtube.com/watch?v=Z_o8BaExmFQ) of using version 5 of xState 
- Xstate [migration guide](https://stately.ai/docs/migration)

```[tasklist]
### Tasks
- [ ] Follow migration guide from https://stately.ai/docs/migration
- [ ] Upgrade xstate in KDS
- [ ] https://github.com/learningequality/kolibri/issues/12646 
```

**Comment by davidkpiano** [comment]
Please let me know if you need any help with this migration - willing to help!

**Comment by MisRob** [comment]
Thanks @davidkpiano, we appreciate it

**Comment by MisRob** [comment]
Thanks @davidkpiano, we appreciate it. Your library has been of such a great help for some of our complex workflows.

**Comment by jredrejo** [comment]
v5.4.1 is the current target
