### ISSUE TITLE
Enhanced Quizzes: UI & UX Updates & Tech Debt Tracker

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11741]
## Overview

This is an issue for tracking various UI issues to be addressed within the updated quiz management experience.

These may be broken out to separate issues in an upcoming iteration and are requirements for the feature, but they can be handled once some of the other issues are addressed.

### Tasks
- [x] #11784

 ![image](https://github.com/learningequality/kolibri/assets/6356129/055c884e-f5c8-4bf7-af01-da964ed29f45)

- [x] #11806
- [x] Write tests for the `useFetchTree` module
- [x] #12033
- [x] #11771
- [x] (Resource Selection) Following up from #11734 -- allow Bookmarks to be selected as well. Bookmarks should be filtered to only display Exercises
- [x] #11786
- [x] #11790
- [x] Follow-up from #11783 -- in that issue we handled the "working resource pool" (aka the user's current selection state while interacting with the Select Resources Side Panel) within the global scope by way of useQuizCreation's `inject/provide` business. This logic could very much have lived within the SelectResources component, except that the component remounts every time we navigate between folders. The refactoring of this should be prioritized once we have resolved the routing issues noted in #11219 
- [x] The `channelsLink` is not working as intended -- should be returning the user back to the list of channels
- [x] Back arrow is duplicated when going to resource selection from section editor
- [x] (Edge case): How to handle "replacement" when the user doesn't have enough questions in the resource pool to account for their replacement? May need to check Figma
- [x] Follow-up clean-up re: Keyword search code -- the PR comment [here](https://github.com/learningequality/kolibri/pull/11887#pullrequestreview-1884119146) has more details but, in short, that PR was merged so that its work can be integrated with some other changes which substantially make the dev workflow better and improve the code overall

**Comment by nucleogenesis** [comment]
Closing this as all items are either resolved or have been made into their own issues ✅
