### ISSUE TITLE
Quiz Creation Select Resources- Implement disabled topic checkbox messaging

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#11790]
## overview 
There is a need to refine the folder selection in Resource Selection with improved messaging around when a use can select a whole folder and why they cannot do so when the checkbox is disabled.

### Guidance 
 1. Users should not be able to select folder's topic tree, If the folder tree looks like this even if  all of the folder's children are exercises. 
```
├── Math
│   ├── Numbers
│   │   ├── Counting to 5
│   ├── Addition
│   │   ├── Make 10
│   ├── Multiplication
│   │   ├── 10s Times Tables
```
2. User can only select the topic if the  topic tree looks like this and or  all of the topic's children are exercises 

```
  ├── Multiplication
  │   ├── 10s Times Tables
```

#### Tasks

- [x] Implement logic to allow topic selection only when all children are available ([hasMore](https://github.com/learningequality/kolibri/blob/66589c69dd0c59c443acf33e54a062ff89af99d7/kolibri/plugins/coach/assets/src/composables/useFetchTree.js#L41) computed prop  is false) and are exercises.
- [ ] If a folder is not able to be selected, do not display the checkbox for it and include in its card a warning icon message "Folder exceeds 12 exercises"
- [ ] If there are any folders which will not have the checkbox due to the logic outlined above, present a message above the listed cards: "Select only folders with 12 or fewer exercises and no subfolders to avoid oversized quizzes. Proceed to choose a smaller folder"

![image](https://github.com/learningequality/kolibri/assets/6356129/c118d5ff-9b8e-412a-8696-8c8e0f86e94c)
