### ISSUE TITLE
Quiz creation: Known issues, bugs, quick fixes

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12037]
## Overview

This is a tasklist of relatively small issues that will later be prioritized. This is put here to track reported issues that can be made into proper GH issues later, as needed.

## Small bugs

```[tasklist]
### Tasks
- [ ] https://github.com/learningequality/kolibri/issues/12064
- [ ] https://github.com/learningequality/kolibri/issues/12065
- [ ] https://github.com/learningequality/kolibri/issues/12134
- [ ] https://github.com/learningequality/kolibri/issues/12097
- [ ] https://github.com/learningequality/kolibri/issues/12135
```

**Comment by nucleogenesis** [comment]
All tasklist items are in their own issues now, closing this as a tracking issue.
