### ISSUE TITLE
Post-setup 'Intro to Kolibri' Onboarding

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#12098]
## Overview
This feature is the process of introducing users to Kolibri's user interface, and key features within the Learn plugin through informative pop-up elements containing tips after the user has completed the device setup process. It's designed to enhance user understanding and engagement with Kolibri UI.

### What problem is it solving?
* Provides a guided introduction to Kolibri for new users.
* Helps users understand the product's value through experience.
* Assists users in using the core product successfully on their own.
* Reduces the chances of user abandonment due frustration and lack of familiarity with Kolibri interface.

### How do we know this feature is successful?
User testing and feedback indicate that the onboarding flow is helpful and improves the initial user experience.

### Who is this feature for?
This feature targets new users who have just completed the setup process for Kolibri, regardless of their setup path (On my own, Learn-only, or Full device). It aims to provide them with a guided introduction to some of the platform's key features and functionalities.

### Project Timeline
Originally planned for Kolibri 0.18, this feature will be completed for GSoC 2025

### Assumptions/Constraints:
* The onboarding flow is only triggered for new users after completing the setup process.
* Each user should only see each tip once.
* The flow is non-intrusive and easy to dismiss for users who don't need it.
* If users select the option to ‘skip', this will bypass the remainder of the post-setup onboarding flow.

### Guidelines:
- Put all strings into one file for the feature. Refer to the `develop` branch for the folder `packages/kolibri-common/strings` and add a new file for the set of strings.
- Create a new component and wrap all of the step components inside of it. All state data will be managed in a shared state.
- Component Outline:
  - The component will receive an array of onboarding steps. Each onboarding step contains a reference target, information about its content and placement, and whether it's active.
  - The component will loop through the steps and render the inline tips for each active step. The inline tips will  include informational content to guide users through the onboarding process.
  - The component responsible for executing each step can use the `popper.js` library in order to create the popover elements and positioning.
  - Users have the option to dismiss the entire onboarding process by clicking the "X" button. When the button is clicked, a method is triggered, setting the completed property to true.
  - Once dismissed/completed, the entire onboarding process is hidden, and users will no longer see the onboarding tips.
- Accessibility Considerations:
  - Inline tips are designed to be screen reader compatible, keyboard accessible, and have sufficient color contrast for readability.
  - Users can navigate and interact with the onboarding process using assistive technologies and keyboard navigation. Users who rely on keyboard navigation should be able to access and interact with the onboarding guide without using a mouse.

### Acceptance criteria
- [ ] Pop-up elements display informational tips about Kolibri's core features post-setup, covering essential functionalities like library navigation, channel exploration, and accessing learning materials.
- [ ] Inline tips offer context-specific guidance within the user interface.
- [ ] Onboarding flow follows the provided Gherkin scenarios, functioning correctly across various setup paths and user scenarios.
- [ ] Users have the option to dismiss or skip the onboarding easily.

### Tasks
- [x] #12102

### Resources
- [Figma specs](https://www.figma.com/design/d0ZHK8Q4NZyVsJxTxCLkRl/Onboarding---GSOC-2025?node-id=260-5074&p=f&t=HKU6ScXrVWvcAMs1-0)
- [Gherkin Scenarios](https://www.notion.so/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b?pvs=4#f22cbf86cf564874804210b3914e6438)

**Comment by JennyPoudel** [comment]
Can I work on this issue?

**Comment by MisRob** [comment]
Hi @JennyPoudel, thanks for volunteering, we appreciate it. This issue is already assigned to a core team member. We welcome contributors on many other issues. There are contributing opportunities in three repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.
