### ISSUE TITLE
EQM: Design updates; Coach reports, Exams' questions view

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12168]
## Overview

@rtibbles and I chatted about some (hopefully) quick updates we can make to better handle the new quiz structure (sections). This is a tasklist outlining the plan and efforts to update the UI in the following ways:

Overall, I'll be exploring a few of these changes and getting feedback on screen recordings throughout.

```[tasklist]
### Tasks
- [ ] (Learner Exam View): The questions list (ie, the buttons that can be clicked to select a question to view) should collapse with the title and description -- perhaps this will need additional design guidance, but a prototype will be attempted (or several w/ screenshots).
- [ ] (Learner Exam View): The clickable accordion headers for the question list should indicate their completion state similarly to how the blue/gray dots do for questions as-is. (Maybe we shouldn't rely on color alone for this though? -- perhaps use an 'unread message dot' type approach or icons?) -- but the point is we need to show when "this section is collapsed and has an unanswered question"
- [ ] (Learner Exam View): The section's title should be a persistent display toward the top of the question's content container
- [ ] (Learner Exam View): On <=tablet view, add an icon button to the right side of the top app bar which will open a question list akin to that which is always visible on larger screens
- [ ] (Coach/Learner Exam Report): The sections should be laid out in an accordion such that the titles are the headers and the way the report view looks now is presented for that section alone. Include metadata on the section header re: completions/failures.
- [ ] (Coach/Learner Exam Report):  On <=tablet, add another dropdown for the sections when they're present
```
