### ISSUE TITLE
Remove `TextTruncatorCss` Vue component in favor of `KTextTruncator`

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#12211]
🌱 **Are you new to the codebase? Welcome and please see [the contributing guidelines](https://github.com/learningequality/kolibri/blob/develop/CONTRIBUTING.md)**

## Description

Remove `TextTruncatorCss` Vue component in favor of `KTextTruncator`

## Background

We moved `TextTruncatorCss` from Kolibri to [Kolibri Design System](https://github.com/learningequality/kolibri-design-system), where it became `KTextTruncator` so now the original `TextTruncatorCss` can be removed from Kolibri.

## Guidance

- [KTextTruncator documentation](https://design-system.learningequality.org/ktexttruncator/)

```[tasklist]
### Tasks
- [ ] Find all places in Kolibri where `TextTruncatorCss` is used and replace it with `KTextTruncator`
- [ ] Then remove `TextTruncatorCss.vue` file from Kolibri codebase
- [ ] Manually preview at least a few places and confirm that text truncation still works as before
```

**Comment by jasonmokk** [comment]
Hello, I'd like to work on this.

**Comment by AlexVelezLl** [comment]
Hi @jasonmokk. Thanks for your interest in taking this issue! I will assign this issue to you =).

**Comment by ankityadav47** [comment]
can you please share this issue is fixed or not?

**Comment by MisRob** [comment]
Hi @ankityadav47, this will be soon fixed. If you'd like to find another one, there are contributing opportunities in three repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories
