### ISSUE TITLE
In Coach, update the quiz creation and management experience to use the `kolibri-common` `useBaseSearch()`

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12624]
The current search implementation in quiz creation is quite limited, only allowing search by keyword.

Instead, this can be updated to expose a side panel overlay of all search metadata in a similar manner to learn, with either search across the entire library, or scoped to a specific topic in the topic tree after navigation.

### Tasks
- [ ] https://github.com/learningequality/kolibri/issues/12519
- [ ] https://github.com/learningequality/kolibri/issues/12520
- [ ] https://github.com/learningequality/kolibri/issues/12521
- [ ] https://github.com/learningequality/kolibri/issues/12522
- [ ] https://github.com/learningequality/kolibri/issues/13035

Example screenshot from Figma of the experience:
![image](https://github.com/user-attachments/assets/3a2cb267-7930-4712-853c-1ad2743f29f4)

[Figma Specs](https://www.figma.com/design/lVJt5ukOrxS9qay0rXy7GC/0.18-Coach-updates?node-id=107-28395&node-type=FRAME)

**Comment by rtibbles** [comment]
Note that closing this issue will also close https://github.com/learningequality/kolibri/issues/7635

**Comment by marcellamaki** [comment]
Closed as completed by sub-issues
