### ISSUE TITLE
Add Python 3.13 support

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12682]
### Prerequisites
- [x] https://github.com/learningequality/le-utils/issues/142
- [x] https://github.com/learningequality/morango/issues/230
- [x] https://github.com/learningequality/morango/issues/234
- [ ] Not actually required - will just have a slight performance degredation for now: https://github.com/learningequality/kolibri/issues/12753

### Tasks
- [X] Add support for the as yet unreleased Python 3.13
- [X] Add to CI version matrices
- [X] Ensure all tests pass
- [ ] Update Windows installer to allow Python 3.13
