### ISSUE TITLE
Update the Plan > Lesson Summary page to reflect both planning and report elements

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12707]
## Overview 
For our information architecture restructuring, we are going to be "squishing together" some of our current pages and components to move us to a different page naming system and organization. 

### Prerequisites
- Run Kolibri or `kolibri-demo` locally to get familiar with the current state of the UX/UI. Make sure you are rebased on top of develop and that you see the new `lessonstemp` path.

### Diff - current state vs new state 
| Plan | Reports |
|---|---|

The new landing page for lessons will combine elements from each to be available at a glance:

### Tasks 

- [ ] Following the `/lessonstemp/` routes pattern, create a `/lessonstemp` route that functions as the temporary "root" lesson page, or landing page, for the lesson
- [ ] The component should be the `LessonSummaryPage`, except with an updated path: 
```
  {
    name: LessonsPageNames.SUMMARY,
    path: '/:classId/plan/lessonstemp/:lessonId',
    component: LessonSummaryPage,
    handler(toRoute) {
      return showLessonSummaryPage(store, toRoute.params);
    },
    meta: {
      titleParts: ['LESSON_NAME', 'CLASS_NAME'],
    },
  },
```
- [ ] Update the table used in `LessonSummaryPage` to include "progress" from reports to the main table; use the same empty states as in report when data is not available (or not yet ready)
- [ ] Add a placeholder to filter by recipients - the filtering action will be done in follow up
- [ ] Add class title at the top of the UI 
- [ ] include the "view learner devices" and print and download option buttons from the reports

### Acceptance Criteria
- all tasks above are completed
- all "report" data is available in the table at a glance
- All UI adjustments to be aligned to the new spec (i.e. moving the "new quiz" button, adding top/bottom borders for table rows for readability, updating or removing strings and titles, etc.)
- The changes do not break the _current_ state of develop, at `/plan/lessons`

### Out of scope 
- Removing the `KTabsPanel` or updating the main navigation titles
