### ISSUE TITLE
Ensure Consistent 400 Response for Invalid Input in Kolibri Public Content APIs with Studio

### ISSUE THREAD

**Issue by ozer550** [learningequality/kolibri#12807]
## Description 

Currently, the Kolibri public content APIs, specifically retrieve function of [ContentNodeTreeViewset](https://github.com/learningequality/kolibri/blob/04f4a38a0dc2b3b31754ffbd0dc324a05af7a122/kolibri/core/content/api.py#L859) and [ImportMetadataViewset](https://github.com/learningequality/kolibri/blob/04f4a38a0dc2b3b31754ffbd0dc324a05af7a122/kolibri/core/content/public_api.py#L16) handle invalid input by returning a 404 response. To ensure consistent API behavior across Kolibri and Studio, we need to update these views to handle invalid input in a way that aligns with the implementation in Studio. 

**Tasks:**
- [ ] Update the retrieve function of ContentNodeTreeViewset and ImportMetadataViewset to return 400 when there is a bad input.
- [ ] Update [test](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/test/test_content_app.py#L516) for TreeViewset.
- [ ] Write new test to ensure the same for ImportMetadataViewset.

**Expected Outcome:**
- Consistency in behavior across APIs.

**References:**

We would want to refactor similar to this [PR](https://github.com/learningequality/studio/pull/4794).

**Comment by manzil-infinity180** [comment]
can I take this issue?

**Comment by AllanOXDi** [comment]
Hi @manzil-infinity180,  Sure you can! I have assigned it to you. Thanks for contributing

**Comment by ozer550** [comment]
Feel free to ask any questions you have on the way @manzil-infinity180 :)

**Comment by rajRishi22** [comment]
Sir , I know that this issue has already been assign but can i work together to solve this problem ?

**Comment by manzil-infinity180** [comment]
Hello @rajRishi22 , I have already solved this issue I will raise pr in some following day. You can take a look at some other issues with no assignee 
Thank you

**Comment by rajRishi22** [comment]
Hello @manzil-infinity180 , I will look into other issues.

**Comment by qmhqmhqmhqmh** [comment]
can I take this issue?

**Comment by MisRob** [comment]
Hi @qmhqmhqmhqmh, thanks for volunteering! It's best to always preview whether an issue has an assignee or no. This one is already taken and even has a pull request linked.

There are other contributing opportunities in several repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](<https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md>)
- [Kolibri Design System Contributing Guidelines](<https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md>)
- [Studio Contributing Guidelines](<https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md>)

You can also see the list of unassigned ["help wanted"](<https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues>) or ["good first issue"](<https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues>) issues across all repositories.

**Comment by m3tal10** [comment]
@manzil-infinity180 , are you still working in this?

I want to work on this issue too if you do not want to continue with this anymore.
