### ISSUE TITLE
Allow coaches to choose when a quiz report should become visible to learner

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12902]
## Overview 

As part of the iterative updates to quizzes, and based on feedback that we have gotten from the community, we want to add an option for coaches to choose when a quiz report becomes visible to learners. The current state, and what should be the default going forward, is that the quiz report (meaning, what the learner views and is able to review in terms of their score and the correct answers) is visible immediately after the learner submits their quiz. 

Based on feedback from the community, there are some situations where this is not ideal, because learners could share the information from the report with others who have not yet submitted their quizzes, especially in situations where the quizzes may not all be completed simultaneously or in a short timeframe.  However, because coaches often don't "end" quizzes through the UI, we will _not_ have this be the default behavior.

To address this, we will add a new field on the base exam - which is inherited by the exam and draft exam - and update both the learner and coach UX to reflect the changes. 

| Description | Reference Image |
|---|---|
| For the coach, a dropdown is added on both the create and edit quiz form, by the title. The default option should be for the quiz to be immediately visible | <img width="697" alt="Image" src="https://github.com/user-attachments/assets/14c9a1f4-bfdc-4492-a7c2-c1e281ff45fa" /> |
| The dropdown is visible and editable as the coach is creating or editing the quiz, and in the quiz information side panel (in a non-edit state) the additional field is visible | <img width="683" alt="Image" src="https://github.com/user-attachments/assets/24d92130-8d02-4981-a88a-d70ba98d95c5" /> |
| For the learner, if the quiz report is not visible until the quiz is ended | <img width="896" alt="Image" src="https://github.com/user-attachments/assets/ec57f407-5afa-4681-92aa-fffd15c6b685" /> |

### Tasks

Please take a look at [the Figma ](https://www.figma.com/design/lVJt5ukOrxS9qay0rXy7GC/0.18-Coach-updates?node-id=474-12035&t=DDj9lWTuB70tyqtj-0) (see "Quiz report Visibility" including "Learner Exp[erience]" below) as not all screenshots are displayed below, and the flow is clearer on the Figma page.

- [ ] Update the `AbstractExam` model, which contains shared fields and methods between the DraftExam and Exam models, to add a field for the "quiz report visibility" (you can choose the name of the field, but something along this line would be good 😄). Using a Boolean field may simplify doing the conditional checks on the learner side, and the options on the coach UI quiz information that is displayed.
- [ ] Add a frontend field in the create and edit exam views on the quiz, and associate the two different value options to the backend field visibility option. Ensure it updates properly on save.
- [ ] Update the places in the UI on the coach side where the new field is displayed (please review figma)
- [ ] Add in conditional "end quiz" behavior - building upon the existing functions, the quiz report should always be set visible = true when the quiz is ended. 
- [ ] Update the learner quiz report card UI - adding a conditional check on the visibility, and preventing navigation to the quiz report if it is not yet ready (for quizzes where the condition is set) 
- [ ] Frontend polling should already handle updating the quiz to accurately reflect when it is "ended" - but check the various places where a learner might encounter a quiz and confirm that polling is working as predicted in these places, and that the quiz data is being updated.

**Comment by Flying-Pegasus** [comment]
@marcellamaki @kollivier Is this issue open, I want to work on thi issue

**Comment by marcellamaki** [comment]
Hi @Flying-Pegasus - thank you for your interest in contributing to Kolibri! As you can see from the empty issue description, this issue is not yet ready for someone to take it up because there are no details provided yet for what needs to be done. 

I know that most of our "help wanted" issues on Kolibri are currently assigned to other community contributors, which may be frustrating, but please use that as a reference when looking for issues that are suitable for the open source community. We will continue to open and tag issues for community contribution now that we have returned from our 2 week end of year office closure, and there will be more opportunities for your contributions in the coming weeks. Happy new year!

**Comment by Flying-Pegasus** [comment]
Okay @marcellamaki Thank you
