### ISSUE TITLE
debian packaging high-level task tracker

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2697]
* [x] [outstanding issues](https://github.com/learningequality/kolibri-installer-debian/milestone/1) (cc @benjaoming)
* [ ] user documentation (cc @radinamatic)
* [ ] testing on multiple platforms
* [ ] le.org UI (cc @khangmach)

**Comment by indirectlylit** [comment]
this issue is not meaningful enough
