### ISSUE TITLE
introduce new technical changelog tracking process

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3134]
### Observed behavior

Notes from discussion at today's dev meeting:

* There are user needs for both a high-level executive summary of changes that can be skimmed, as well as a detailed technical overview with links to the code-base that can be searched and analyzed.
* We're already diligent about adding github milestones to every issue and PR, which creates a detailed and complete overview of everything that happened in a release. However, this overview is too noisy for general consumption.
* Asking developers to manually update another (more detailed) changelog would introduce too much friction to the development process, especially given that most information is already contained in the github milestone overview. 

### New process overview

Add a new github label named <kbd>changelog</kbd>. Update our PR template to include an action item like:

 * [ ] If this change results in a salient user-facing change, the PR or a related issue is tagged with the **_changelog_** label.

Before future releases, we'll go through and make sure that all items with the 'changelog' label have clear, meaningful titles. Then, from the high-level changelog, we can link to a github overview which filters by milestone + changelog label.

### Context

See initial discussion from @benjaoming in #3105

### TO-DO

* [x] Add new label, and start applying it to releases from 0.7.1 and beyond
* [x] Update PR template to include new language about use of the label
* [x] Update release process checklist to include language about cleaning up titles of labeled items

**Comment by radinamatic** [comment]
Looks right on point to me @indirectlylit! 👍

**Comment by benjaoming** [comment]
I cannot rule out that I will ask for more :) But I like the direction of this, and it's definitely useful for the insights both for developers, historical background, blog post authors, and curious contributors, deployment architects etc. 👍

**Comment by benjaoming** [comment]
hey, we might get a better workflow here once the user docs are only maintained in kolibri-docs -- let's consider that at least, and see how we can collect, sift, and communicate the release notes once they have to be put in a separate repo, anyways! :)

**Comment by benjaoming** [comment]
@indirectlylit is the tag up yet? could we start using it already now and close this issue?

**Comment by indirectlylit** [comment]
The new label is ready: https://github.com/learningequality/kolibri/issues?q=label%3Achangelog+is%3Aclosed

however I still need to update the PR template and release process notes
