### ISSUE TITLE
follow-up from quiz updates

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4716]
### Observed behavior

follow-up from #4667

### Expected behavior

* [x] lots of feedback from https://docs.google.com/document/d/1QeRghWCFdJgWV627DaIWRM80pJ3IkJr_TRQjI4uJXEw/edit
* [x] add incrementing numbers to title
* [ ] ~learner and report views~ will be in another PR
* [x] make sure preview shows answer after drag
* [ ] ~improve preview layout~ moved to #4766
* [ ] ~validation of duplicate titles~ #4626
* [ ] ~drag/drop fixes and accessibility - see e.g.  @radinamatic's [comments](https://github.com/learningequality/kolibri/pull/4667#issuecomment-453695739)~ moved to #4764
* [ ] ~associate `data_model_version` with model rather than serializer~ moved to #4765
* [x] question numbers can go negative: ![question numbers](https://user-images.githubusercontent.com/2367265/51195393-d2fb5a00-18a1-11e9-9ba3-e984a9b13237.gif)
* [x] cannot move last item: ![moving last object in list](https://user-images.githubusercontent.com/2367265/51195425-e3abd000-18a1-11e9-854e-8abee9bca249.gif)
* [x] delayed change:  ![delayed change](https://user-images.githubusercontent.com/2367265/51195485-00480800-18a2-11e9-9f0c-ac362b883348.gif)
* [x] not enough questions error: ![not enough questions](https://user-images.githubusercontent.com/2367265/51491115-37b32a80-1d62-11e9-8e2d-3df22bb0bd40.gif)
