### ISSUE TITLE
♻️ Tasks can be restarted on the UI

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7930]
Sub-issues for epic:

Either the restart functionality does not exist or it does not use the new task restart API implemented in #7905 

### Tasks
- [ ] Restart facility import
- [x] Restart facility sync
- [ ] Restart facility deletion
- [ ] Restart setup wizard facility import
- [x] Restart channel import/export/deletion
- [ ] Restart user CSV import/export
- [ ] Restart logs CSV import
