### ISSUE TITLE
Team is notified when a contributor posts a comment to a GitHub issue

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9521]
## Summary

Create a GitHub action that sends a Slack notification to #dev-community channel whenever someone who's not a member of the [Learning Equality Team](https://github.com/orgs/learningequality/people) comments on a GitHub issue

## Acceptance criteria

- [x] A notification is sent to #dev-community Slack channel any time (not just a first time) an external person comments on a GitHub issue
- [x] The notification is *not* sent when an external person comments on a pull request
- [x] The action uses only official GitHub and Slack 3rd party actions. Other actions can be used for inspiration, but the logic should be implemented by us (for security and to prevent regressions when updating versions).

```[tasklist]
### Tasks
- [ ] On [`issue_comment`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment), find out if the comment was done on a pull request or an issue ([issue_comment on issues only or pull requests only](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only)). Continue only if it's an issue comment.
- [ ] Find out if an author of the issue comment is a member of the [Learning Equality Team](https://github.com/orgs/learningequality/people). See [`comment.author_association`](https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment) (hidden in "Properties of comment" toggle) and [CommentAuthorAssociation](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation). Continue only if the author is not `MEMBER` and neither `OWNER`.
- [ ] Send the notification about the comment to the #dev-community Slack channel. [The official Slack action](https://github.com/marketplace/actions/slack-send) can be used.
```

**Comment by marcellamaki** [comment]
The first step of this would just be investigation and proposing an implementation

**Comment by vkWeb** [comment]
@MisRob closing this since its done I feel. :tada:
